baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'CERNBox Filepicker'
theme = 'docsy'

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
sidebar_menu_foldable = false
sidebar_cache_limit = 10
# Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true

[params.links]
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/cernbox/file-picker-wrapper"
  icon = "fab fa-github"
  desc = "Development takes place here!"
